LATEXMK_OPTIONS := -synctex=1 $\
				   -interaction=nonstopmode $\
				   -recorder $\
				   -file-line-error $\
				   -shell-escape $\
				   -halt-on-error $\
				   -pdf
LATEXMK_PREVIEW := $(LATEXMK_OPTIONS) -pvc
CHKTEX_OPTIONS := --localrc ./.chktexrc $\
				  --headererr $\
				  --inputfiles $\
				  --format=1 $\
				  --verbosity=2
LATEXINDENT_OPTIONS := --local=indentconfig.yaml $\
					   --overwrite

all:
	latexmk $(LATEXMK_OPTIONS) main.tex

# remove backup files that generated by latexindent.pl
cleanbak:
	rm -f $(shell find . -regex ".*\.\(bak\d*\)$$")

# remove untracked and ignored files
cleangit:
	git clean -f -d -X

chktex:
	chktex $(CHKTEX_OPTIONS) $(shell find . -name "*.tex")

# format tex, cls, sty files
# all files and directories should not contain any white space in their names
formatall:
	for file in $(shell find . -regex ".*\.\(tex\|cls\|sty\)\$$"); do \
		echo "\n\n"; \
		echo "Formatting $$file ...\n"; \
		latexindent $(LATEXINDENT_OPTIONS) $$file; \
	done

updatecls:
	mkdir -p $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class
	cp *.cls $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class

%.pdf: %.tex
	latexmk $(LATEXMK_PREVIEW) -outdir=$(shell dirname $(MAKECMDGOALS)) $<

# remove auxiliary files and pdf, dvi files
%.clean: %.tex
	latexmk -C -outdir=$(shell dirname $(MAKECMDGOALS)) $<

# remove auxiliary files that generated while latexmk running
%.cleanaux: %.tex
	latexmk -C -outdir=$(shell dirname $(MAKECMDGOALS)) $<

# to build chapter0, run make chapter0 -B
# to build section1 of chapter1, run make chapter1/section1 -B
# you might need to run make clean first
%:
	if [ -d $(MAKECMDGOALS) ]; then \
		latexmk $(LATEXMK_OPTIONS) -outdir=$(MAKECMDGOALS) "$(lastword $(subst /, ,$(realpath $(MAKECMDGOALS)))).tex"; \
	fi

	if [ -f $(MAKECMDGOALS) ]; then \
		latexmk $(LATEXMK_OPTIONS) -outdir=$(shell dirname $(MAKECMDGOALS)) $(MAKECMDGOALS); \
	fi

	if [ -f "$(MAKECMDGOALS).tex" ]; then \
		latexmk $(LATEXMK_OPTIONS) -outdir=$(shell dirname $(MAKECMDGOALS)) "$(MAKECMDGOALS).tex"; \
	fi
