LATEXMK_OPTIONS := -synctex=1 $\
				   -interaction=nonstopmode $\
				   -recorder $\
				   -file-line-error $\
				   -shell-escape $\
				   -halt-on-error $\
				   -pdf
CHKTEX_OPTIONS := --localrc ./.chktexrc $\
				  --headererr $\
				  --inputfiles $\
				  --format=1 $\
				  --verbosity=2
LATEXINDENT_OPTIONS := --local=indentconfig.yaml $\
					   --overwrite

all:
	latexmk $(LATEXMK_OPTIONS) main.tex

# remove untracked and ignored files
clean:
	git clean -f
	git clean -f -d
	git clean -f -d -X

# remove backup files that generated by latexindent.pl
cleanbak:
	rm -f $(shell find . -regex ".*\.\(bak\d*\)$$")

# remove auxiliary files that generated while latexmk running
cleanaux:
	rm -f $(shell find . -regex ".*\.\(aux\|fdb_latexmk\|fls\|log\|sta\|synctex\.gz\|toc\)$$")

# remove pdf, dvi files
cleanoutput:
	rm -f $(shell find . -regex ".*\.\(pdf\|dvi\)$$")

chktex:
	chktex $(CHKTEX_OPTIONS) $(shell find . -name "*.tex")

# format tex, cls, sty files
# all files and directories should not contain any white space in their names
formatall:
	for file in $(shell find . -regex ".*\.\(tex\|cls\|sty\)\$$"); do \
		echo "\n\n"; \
		echo "Formatting $$file ...\n"; \
		latexindent $(LATEXINDENT_OPTIONS) $$file; \
	done

updatecls:
	mkdir -p $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class
	cp *.cls $(shell kpsewhich -var-value=TEXMFHOME)/tex/latex/local/class

# to build chapter0, run make chapter0 -B
# to build section1 of chapter1, run make chapter1/section1 -B
# you might need to run make clean first
%:
	latexmk $(LATEXMK_OPTIONS) -outdir=$(MAKECMDGOALS) $(shell find $(MAKECMDGOALS) -maxdepth 1 -regex ".*\.tex\$$" -not -type d)
